e=set()
n=int(input("enter number 1"))
e.add(n)
n=int(input("enter number 1"))
e.add(n)
n=int(input("enter number 1"))
e.add(n)
n=int(input("enter number 1"))
e.add(n)
print(e)
#if two values are same in the pyhton then the datatype wont change a thing