marks=[]
f1=int(input(("enter marks:")))
marks.append(f1)
f2=int(input(("enter marks:")))
marks.append(f2)
f3=int(input(("enter marks:")))
marks.append(f3)
f4=int(input(("enter marks:")))
marks.append(f4)
marks.sort()
print(marks)
print(sum(marks))